sudo: false
language: java
install: ./gradlew wpi
script: ./gradlew build bintrayUpload
jdk: oraclejdk8
cards:
  enabled:
    - "master"
  colors:
    background: "#000000"
    top-border: "#F7E078"
    passed: "#17c700"
