sudo: false
language: java
install: ./gradlew wpi
script: ./gradlew wpi clean jar -PciBuild=true
jdk: oraclejdk8
deploy:
  - provider: releases
    api_key:
      secure: R1YsQIVy+SdDBbJpwLrAdnh5w8Xp4UT2ExsrCLOHbfv1NAq/vPrt8/iIs8o2nj6Z7KY7ZZyDrGoREVVG5WKWCd0rVSMXRD8v+JHSxSRhdYnpc6VyOEB4A2LbQQi4bEal+YzJPTDsyP2fNPQH8srDozcfiJumaF9O/ob8MczSVx/EZCqFgY3Mmk8dMPzguiCU92ibYiajgpDETjRyT+3hsRYsFM4DNMoXPI/1NZJJtZSpyMJQLuz0s54u3GBxjv+d4luTq7S/hyKmsgV7YU3/RSWUnIqCvPqJA301XwLtT2Xm/rPPaI/rybvtiZTczaE9Kmhzop2mW6nFZGVPRnDK8ZuYkE3EM4FYYK7PCGtfeXiOL1UGZiVeoLNWEfMN6VctrIhZjnyqLSLJes0H0lfVdrQiIgS1vSfTsk39lm2JD1Cu9mCgpoXzkuoWCxgPFC8Ys9hShRCOFm7VLzh+aznUxAtHtOtA5CCwgejoP1hIPE+dfYwE69aKL+MXkALAcnNqjqM2nlVu4nB9cSIQ+oimAQntdb80DncXihNsurwoAhmPe2IC+k3n3S52ijWzxpSCmiud7oVPCbqCkTEIJkYED+mg1AZqPlkv+5rjDRxEo25UOWD3EhvNT+WQjbeasmEwBQweyjdBoUSCDCRuCTULdrN5I0izgZ/XFDEHc9ZOuuY=
    file: build/libs/CiDemo.jar
    on:
      tags: true
  - provider: bintray
    file: bintraydescriptor.json
    user: johnrudolflewis
    key:
      secure: aket36PP9cgzLCivTo8odlT57kKf5CJZP4RcHA43TGtaCraSDQKpnQoY7xiDz9RiKFYRTNmUWt1wxNlKvcW8F1UnylK02cI5HCKlX+fQ7tbKg470FHNauYNcDPI3czhuoKFtZNysrc3CnXt6pDpAPyYhaORgENJfNpSmVeawtYHF5oO5nRaDIBUksNYrwtKsHw3q3qGCqimwBsFQUCRMfMUcCKqoiY4xZkxrqNYBRYH+2eKSYSgDhO4tSBjgW+3UGGoD1BFc+qY+4/VsTEmNG3pI+IkTHYNSaEWSsj6QJiVldse1Izj2KQy1nDoVxHUeaHVKXEJ9oae5G4kKL93gM2S7q9sXHa8yTLcrs/3QER2sNRc15DfNbGr8DfoCHAfl/cgDJzGd5jMrzgz761ZMK6+c0/TIYMkMKdZQhe53/LNNLyxKH7W4ShfGEt4K/sU5T+Rq4SOPJOT5Mrm0epUvrIbWH2g2GB5XNk8WtNaKcBbwgyhfrTo7yQXVBfg0/fEJcDooLVe0i6VOBPo4xu+g5IKJ1WqIMxzMZXm88iAiq8eyK9Dd1rs1DDzly97i0CFkvfyisXxn1+TP4RP+oICTg7optI7U2J2NNq7kCvMN4V5Tnj69kpt+H/sVEJLnIRBOJ7RsRyG5Dv3Zal7pjrAMFAZIZfY/LnBGKZuPt8RjGhg=
